"""
Alert model: represents a security alert generated by the correlation engine
or detection rules.

Alerts can be acknowledged, escalated, and grouped into incidents.
"""

import uuid
import json
from datetime import datetime, timezone
from enum import Enum
from collections import defaultdict


class AlertStatus(Enum):
    """Lifecycle status of an alert."""
    OPEN = "open"           # New, unreviewed
    ACKNOWLEDGED = "ack"    # Someone is looking at it
    INVESTIGATING = "investigating"  # Active investigation
    ESCALATED = "escalated"  # Escalated to higher tier
    RESOLVED = "resolved"    # Resolved (false positive or handled)
    CLOSED = "closed"        # Closed
    SUPPRESSED = "suppressed"  # Suppressed by rule
    REOPENED = "reopened"    # Reopened after being closed


class AlertSeverity(Enum):
    """Severity levels for alerts."""
    INFO = 1
    LOW = 2
    MEDIUM = 3
    HIGH = 4
    CRITICAL = 5

    @classmethod
    def from_string(cls, name):
        mapping = {
            "info": cls.INFO, "low": cls.LOW, "medium": cls.MEDIUM,
            "high": cls.HIGH, "critical": cls.CRITICAL,
        }
        return mapping.get(name.lower(), cls.LOW)

    def __str__(self):
        return self.name.lower()

    def to_label(self):
        labels = {1: "Info", 2: "Low", 3: "Medium", 4: "High", 5: "Critical"}
        return labels[self.value]

    @property
    def weight(self):
        """Numerical weight for sorting."""
        return self.value


class AlertNote:
    """A note attached to an alert by an analyst."""

    __slots__ = ("id", "text", "author", "timestamp", "note_type")

    def __init__(self, text, author="system", note_type="comment"):
        self.id = str(uuid.uuid4())[:8]
        self.text = text
        self.author = author
        self.timestamp = datetime.now(timezone.utc)
        self.note_type = note_type

    def to_dict(self):
        return {
            "id": self.id,
            "text": self.text,
            "author": self.author,
            "timestamp": self.timestamp.isoformat(),
            "type": self.note_type,
        }


class AlertAcknowledgement:
    """Record of who acknowledged an alert and when."""

    __slots__ = ("user", "timestamp", "reason", "duration")

    def __init__(self, user, reason="", duration=3600):
        self.user = user
        self.timestamp = datetime.now(timezone.utc)
        self.reason = reason
        self.duration = duration  # seconds

    def is_expired(self, now=None):
        """Check if the acknowledgement has expired."""
        if now is None:
            now = datetime.now(timezone.utc)
        elapsed = (now - self.timestamp).total_seconds()
        return elapsed > self.duration

    def to_dict(self):
        return {
            "user": self.user,
            "timestamp": self.timestamp.isoformat(),
            "reason": self.reason,
            "duration": self.duration,
        }


class Alert:
    """
    A security alert generated by the detection or correlation engine.

    An alert references one or more events, has a severity, lifecycle status,
    and supports analyst workflow (acknowledge, note, resolve).
    """

    # Fields that are serialized
    SERIALIZABLE_FIELDS = (
        "alert_id", "title", "description", "severity", "status",
        "rule_id", "rule_name", "rule_type", "category",
        "source_events", "source_event_count", "first_seen",
        "last_seen", "created_at", "updated_at", "resolved_at",
        "owner", "acknowledgement", "notes", "tags", "mitre_attack",
        "risk_score", "confidence", "entities", "evidence",
        "recommended_actions", "false_positive_probability",
        "related_alerts", "incident_id", "metadata",
    )

    def __init__(self, **kwargs):
        self.alert_id = kwargs.get("alert_id") or f"ALR-{uuid.uuid4().hex[:12].upper()}"
        self.title = kwargs.get("title", "Untitled Alert")
        self.description = kwargs.get("description", "")
        self.severity = self._parse_severity(kwargs.get("severity", "medium"))
        self.status = AlertStatus(kwargs.get("status", AlertStatus.OPEN.value))
        self.rule_id = kwargs.get("rule_id", "")
        self.rule_name = kwargs.get("rule_name", "")
        self.rule_type = kwargs.get("rule_type", "detection")
        self.category = kwargs.get("category", "security")

        self.source_events = kwargs.get("source_events", [])
        self.source_event_count = kwargs.get("source_event_count", len(self.source_events))

        now = datetime.now(timezone.utc)
        self.first_seen = kwargs.get("first_seen", now)
        self.last_seen = kwargs.get("last_seen", now)
        self.created_at = kwargs.get("created_at", now)
        self.updated_at = kwargs.get("updated_at", now)
        self.resolved_at = kwargs.get("resolved_at")

        self.owner = kwargs.get("owner")
        self.acknowledgement = kwargs.get("acknowledgement")
        self.notes = kwargs.get("notes", [])
        self.tags = kwargs.get("tags", [])
        self.mitre_attack = kwargs.get("mitre_attack", [])
        self.risk_score = kwargs.get("risk_score", 0.0)
        self.confidence = kwargs.get("confidence", 0.5)
        self.entities = kwargs.get("entities", {})
        self.evidence = kwargs.get("evidence", [])
        self.recommended_actions = kwargs.get("recommended_actions", [])
        self.false_positive_probability = kwargs.get("false_positive_probability", 0.0)
        self.related_alerts = kwargs.get("related_alerts", [])
        self.incident_id = kwargs.get("incident_id")
        self.metadata = kwargs.get("metadata", {})

    @staticmethod
    def _parse_severity(value):
        """Parse severity from string, int, or AlertSeverity."""
        if isinstance(value, AlertSeverity):
            return value
        if isinstance(value, int) and 1 <= value <= 5:
            return AlertSeverity(value)
        if isinstance(value, str):
            return AlertSeverity.from_string(value)
        return AlertSeverity.MEDIUM

    @property
    def is_open(self):
        return self.status in (AlertStatus.OPEN, AlertStatus.REOPENED, AlertStatus.ESCALATED)

    @property
    def is_acked(self):
        return self.status == AlertStatus.ACKNOWLEDGED and self.acknowledgement is not None

    @property
    def age(self):
        """Age of alert in seconds since creation."""
        now = datetime.now(timezone.utc)
        return (now - self.created_at).total_seconds()

    @property
    def severity_label(self):
        return self.severity.to_label()

    def acknowledge(self, user, reason="", duration=3600):
        """Acknowledge the alert."""
        self.status = AlertStatus.ACKNOWLEDGED
        self.owner = user
        self.acknowledgement = AlertAcknowledgement(user, reason, duration)
        self.updated_at = datetime.now(timezone.utc)
        self.add_note(f"Alert acknowledged by {user}: {reason}", user, "ack")

    def unacknowledge(self):
        """Remove acknowledgement."""
        self.status = AlertStatus.OPEN
        self.acknowledgement = None
        self.updated_at = datetime.now(timezone.utc)

    def escalate(self, user, reason=""):
        """Escalate the alert to higher severity/tier."""
        if self.severity.value < AlertSeverity.HIGH.value:
            self.severity = AlertSeverity(self.severity.value + 1)
        self.status = AlertStatus.ESCALATED
        self.updated_at = datetime.now(timezone.utc)
        self.add_note(f"Escalated by {user}: {reason}", user, "escalation")

    def resolve(self, user, resolution_note=""):
        """Mark the alert as resolved."""
        self.status = AlertStatus.RESOLVED
        self.owner = user
        self.resolved_at = datetime.now(timezone.utc)
        self.updated_at = self.resolved_at
        if resolution_note:
            self.add_note(f"Resolved by {user}: {resolution_note}", user, "resolution")

    def close(self, user, close_reason=""):
        """Close the alert."""
        self.status = AlertStatus.CLOSED
        self.updated_at = datetime.now(timezone.utc)
        if close_reason:
            self.add_note(f"Closed by {user}: {close_reason}", user, "close")

    def reopen(self, user, reason=""):
        """Reopen a closed/resolved alert."""
        self.status = AlertStatus.REOPENED
        self.updated_at = datetime.now(timezone.utc)
        self.add_note(f"Reopened by {user}: {reason}", user, "reopen")

    def suppress(self, user, duration=None, reason=""):
        """Suppress the alert."""
        self.status = AlertStatus.SUPPRESSED
        self.updated_at = datetime.now(timezone.utc)
        self.add_note(f"Suppressed by {user}: {reason}", user, "suppress")

    def add_note(self, text, author="system", note_type="comment"):
        """Add a note to the alert."""
        note = AlertNote(text, author, note_type)
        self.notes.append(note)
        self.updated_at = datetime.now(timezone.utc)
        return note

    def add_event(self, event_id):
        """Add a source event reference."""
        if event_id not in self.source_events:
            self.source_events.append(event_id)
            self.source_event_count = len(self.source_events)
            self.updated_at = datetime.now(timezone.utc)

    def add_evidence(self, evidence):
        """Add evidence to the alert."""
        if isinstance(evidence, str):
            evidence = {"description": evidence}
        evidence.setdefault("timestamp", datetime.now(timezone.utc).isoformat())
        self.evidence.append(evidence)

    def add_tag(self, tag):
        """Add a tag."""
        if tag not in self.tags:
            self.tags.append(tag)

    def add_related(self, alert_id):
        """Add a related alert reference."""
        if alert_id not in self.related_alerts and alert_id != self.alert_id:
            self.related_alerts.append(alert_id)

    def update_severity(self, severity):
        """Update the alert severity."""
        self.severity = self._parse_severity(severity)
        self.updated_at = datetime.now(timezone.utc)

    def merge(self, other):
        """Merge another alert into this one."""
        if not isinstance(other, Alert):
            return
        for eid in other.source_events:
            self.add_event(eid)
        for note in other.notes:
            self.notes.append(note)
        for tag in other.tags:
            self.add_tag(tag)
        for technique in other.mitre_attack:
            if technique not in self.mitre_attack:
                self.mitre_attack.append(technique)
        for alert_id in other.related_alerts:
            self.add_related(alert_id)
        if other.last_seen and other.last_seen > (self.last_seen or datetime.min.replace(tzinfo=timezone.utc)):
            self.last_seen = other.last_seen
        if other.first_seen and (self.first_seen is None or other.first_seen < self.first_seen):
            self.first_seen = other.first_seen
        self.risk_score = max(self.risk_score, other.risk_score)
        self.source_event_count = len(self.source_events)
        self.updated_at = datetime.now(timezone.utc)

    def to_dict(self):
        """Serialize alert to dictionary."""
        result = {}
        for field in self.SERIALIZABLE_FIELDS:
            val = getattr(self, field, None)
            if isinstance(val, datetime):
                result[field] = val.isoformat()
            elif isinstance(val, AlertSeverity):
                result[field] = val.value
            elif isinstance(val, AlertStatus):
                result[field] = val.value
            elif isinstance(val, AlertAcknowledgement):
                result[field] = val.to_dict()
            elif isinstance(val, list) and val and isinstance(val[0], AlertNote):
                result[field] = [n.to_dict() for n in val]
            elif isinstance(val, dict):
                result[field] = dict(val)
            elif isinstance(val, list):
                result[field] = list(val)
            else:
                result[field] = val
        return result

    def to_json(self, indent=None):
        """Serialize to JSON."""
        return json.dumps(self.to_dict(), indent=indent, default=str)

    @classmethod
    def from_dict(cls, data):
        """Create an Alert from a dictionary."""
        return cls(**data)

    def __repr__(self):
        return (f"Alert(id={self.alert_id}, sev={self.severity_label}, "
                f"status={self.status.value}, rule={self.rule_name})")

    def __eq__(self, other):
        if not isinstance(other, Alert):
            return False
        return self.alert_id == other.alert_id

    def __hash__(self):
        return hash(self.alert_id)
